# Site settings
title: Hax!
email: sushant.dinesh94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official blog of No Internet Access.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://NIA-ctf.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

authors:
  sushant:
    name: Sushant Dinesh
    display_name: 322
    gravatar:
    email: sushant.dinesh94@gmail.com
    github: sushant94
  
  karthik:
    name: Karthik Senthil
    display_name: 10k-MMR
    gravatar:
    email: karthik.senthil94@gmail.com
    github: karthiksenthil
  
  sriram:
    name: Sriram Rao
    display_name: PPed
    email: sriramrao04@gmail.com
    gravatar:
    github: sriram-rao
