# Site settings
title: Hax!
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Official blog for No Internet Access CTF team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://NIA-ctf.github.io" # the base hostname & protocol for your site
#twitter_username:
#github_username:

# Build settings
markdown: kramdown
